export const nativeVisualContract = {
  contractVersion: "1.0.0",
  sourceApplication: "RonecaPlayTV Android Native",
  sourceVersionName: "2.2.1",
  sourceVersionCode: 23,
  units: {
    layout: "dp",
    typography: "sp",
  },
  colors: {
    background: "#050505",
    backgroundSoft: "#090806",
    navigationBackground: "#080706",
    surface: "#11100E",
    surfaceRaised: "#191713",
    surfaceOverlay: "rgba(17, 16, 14, 0.902)",
    border: "#302A1E",
    divider: "#211E18",
    primary: "#E8C768",
    primaryStrong: "#FFDB73",
    primarySoft: "rgba(232, 199, 104, 0.20)",
    red: "#C62828",
    redStrong: "#FF3B30",
    redSoft: "rgba(198, 40, 40, 0.20)",
    purple: "#C9AE68",
    orange: "#E9A44F",
    green: "#73C98C",
    yellow: "#E8C768",
    error: "#FF6868",
    textPrimary: "#F7F4EC",
    bodyText: "#D8D2C5",
    textSecondary: "#A39D91",
    textMuted: "#69645B",
  },
  shapes: {
    small: 8,
    medium: 12,
    card: 14,
    hero: 18,
    large: 24,
    pill: 999,
  },
  focus: {
    borderWidth: 2,
    restingBorderWidth: 1,
    primaryColor: "#E8C768",
    alternateColor: "#FF3B30",
    focusedSurface: "#191713",
    activationKeys: ["center", "enter", "numpadEnter", "space"],
    neverStealFocusWhileTyping: true,
  },
  television: {
    navigationRailWidth: 82,
    navigationItemWidth: 60,
    navigationItemHeight: 48,
    navigationItemRadius: 11,
    screenHorizontalPadding: 24,
    screenTopPadding: 16,
    screenBottomPadding: 28,
    catalogHeaderTitleSize: 25,
    catalogCounterSize: 12,
    catalogSearchWeight: 0.66,
    catalogTitleWeight: 0.34,
    moviesAndSeriesColumns: 6,
    moviesAndSeriesHorizontalGap: 11,
    moviesAndSeriesVerticalGap: 12,
    channelsColumns: 3,
    channelsHorizontalGap: 10,
    channelsVerticalGap: 8,
    posterAspectRatio: 2 / 3,
    homeHeroHeight: 236,
    homeExploreRailWidth: 254,
    homeHeroGap: 18,
    detailHorizontalPadding: 28,
    detailCoverWidth: 210,
    detailCoverHeight: 315,
    detailColumnsGap: 26,
  },
  mobile: {
    screenHorizontalPadding: 18,
    screenTopPadding: 18,
    screenBottomPadding: 28,
    catalogColumns: 2,
    catalogHorizontalGap: 10,
    catalogVerticalGap: 14,
    bottomNavigationHeight: 55,
    posterAspectRatio: 2 / 3,
    homeHeroHeight: 232,
  },
  typography: {
    brandLetterSpacing: 1.8,
    brandSizeTelevision: 10,
    homeTitleTelevision: 26,
    homeTitleMobile: 22,
    detailTitleTelevision: 32,
    detailTitleMobile: 27,
    sectionTitleTelevision: 20,
    sectionTitleMobile: 17,
    bodyTelevision: 15,
    bodyMobile: 14,
  },
  navigationOrder: [
    "home",
    "channels",
    "movies",
    "series",
    "myList",
    "settings",
  ],
} as const;

export type NativeVisualContract = typeof nativeVisualContract;
